config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root :to =>"homes#top"
  get "home/about"=>"homes#about"
  get "/searches", to: "searches#search"
  devise_for :users
  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resource :favorites, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
  end
  resources :users, only: [:index,:show,:edit,:update] do
    get "search", to: "users#search"
    resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
  end  
  resources :chats, only: [:show, :create]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  
  belongs_to :user
  belongs_to :book
  
end

app/controllers/post_comments_controller.rb
class PostCommentsController < ApplicationController
  
  def create
    book = Book.find(params[:book_id])
    @comment = current_user.post_comments.new(post_comment_params)
    @comment.book_id = book.id
    @comment.save
    
  end
  
  def destroy
   @comment = PostComment.find_by(id: params[:id], book_id: params[:book_id])
   @comment.destroy
  end
  
  private
  
  def post_comment_params
    params.require(:post_comment).permit(:comment)
  end
  
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/views/post_comments/_comment.html.erb
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
  コメント
</button>

<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">コメント内容</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= form_with model:[book, post_comment], local: false do |f| %>
          <%= f.text_area :comment, row: '5', class:"form-control form-control-lg" %>
          <div class="text-right">
            <%= f.submit "送信", class: "btn btn-primary mt-2" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/post_comments/_count.html.erb
<%= "コメント数:#{book.post_comments.count}" %>

app/views/post_comments/_post.html.erb
<table>
  <tbody>
    <% book.post_comments.each do |post_comment| %>
    <tr>
      <td>
        <%= link_to user_path(post_comment.user) do %>
          <%= image_tag post_comment.user.get_profile_image(50, 50) %>
          <%= post_comment.user.name %>
        <% end %>
      </td>
      <td>
        <%= simple_format post_comment.comment %>
      </td>
      <td>
        <% if post_comment.user == current_user %>
        <%= link_to "Destroy", book_post_comment_path(post_comment.book, post_comment), method: :delete, remote: true, class: "btn btn-sm btn-danger" %>
        <% end %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>



  
  
  

app/views/post_comments/create.js.erb
$('.comment').html("<%= j(render "post_comments/post", book: @comment.book) %>");
$('.count').html("<%= j(render "post_comments/count", book: @comment.book) %>");
$("textarea").val("");
$('#exampleModal').modal('hide');
$('body').removeClass('modal-open');
$('.modal-backdrop').remove();

app/views/post_comments/destroy.js.erb
$('.comment').html("<%= j(render "post_comments/post", book: @comment.book) %>");
$('.count').html("<%= j(render "post_comments/count", book: @comment.book) %>");