config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root :to =>"homes#top"
  get "home/about"=>"homes#about"
  get "/searches", to: "searches#search"
  devise_for :users
  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resource :favorites, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
  end
  resources :users, only: [:index,:show,:edit,:update] do
    get "search", to: "users#search"
    resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
  end  
  resources :chats, only: [:show, :create]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord
  
  belongs_to  :user
  has_many :favorites, dependent: :destroy
  has_many :favorites_users, through: :favorites, source: :user
  has_many :post_comments, dependent: :destroy
  
  # いいねランキング
  has_many :week_favorites, -> { wehere(created_at: ((Time.current.at_end_of_day - 6.day).at_beginning_of_day)..(Time.current.at_end_of_day)) }, class_name: 'Favorite'
  
  # 閲覧数
  has_many :view_counts, dependent: :destroy
  
  # 前日比
  scope :created_today, -> { where(created_at: Time.zone.now.all_day) }
  scope :created_yesterday, -> { where(created_at: 1.day.ago.all_day) }
   # 過去７日分の投稿数一覧
  scope :created_2days, -> { where(created_at: 2.days.ago.all_day) }
  scope :created_3days, -> { where(created_at: 3.days.ago.all_day) }
  scope :created_4days, -> { where(created_at: 4.days.ago.all_day) }
  scope :created_5days, -> { where(created_at: 5.days.ago.all_day) }
  scope :created_6days, -> { where(created_at: 6.days.ago.all_day) }
  
  # 前週比
  scope :created_this_week, -> { where(created_at: 6.day.ago.beginning_of_day..Time.zone.now.end_of_day) }
  scope :created_last_week, -> { where(created_at: 2.week.ago.beginning_of_day..1.week.ago.end_of_day) }
  
 
  
  validates :title,presence:true
  validates :body,presence:true,length:{maximum:200}
  
   def favorited_by?(user)
     self.favorites.exists?(user_id: user.id)
   end
   
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def show
    @books = Book.new
    @book = Book.find(params[:id])
    unless ViewCount.find_by(user_id: current_user.id, book_id: @book.id)
      current_user.view_counts.create(book_id: @book.id)
    end
    @user = @book.user
    @post_comment = PostComment.new
  end

  def index
    to  = Time.current.at_end_of_day
    from  = (to - 6.day).at_beginning_of_day
    @books = Book.all.sort {|a,b| 
      b.favorites.where(created_at: from...to).size <=> 
      a.favorites.where(created_at: from...to).size
    }
    @book_new = Book.new
    @user = current_user
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    @user = current_user
    if @book.save
      redirect_to book_path(@book), notice: "You have created book successfully."
    else
      @books = Book.all
      render 'index'
    end
  end

  def edit
    @book = Book.find(params[:id])
    user = @book.user
    unless user == current_user
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    @user = @book.user
    if @book.update(book_params)
      redirect_to book_path(@book.id), notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end
  
  # def rank
    # @books = Book.last_week
  # end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end
  
  def editing_user
    book = Book.find(params[:id])
    if book.user != current_user
      redirect_to books_path
    end
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= form_with model:book, local:true do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control book_title' %>
  </div>
  <div class="form-group">
    <%= f.label :opinion %>
    <%= f.text_area :body, class: 'form-control book_body' %>
  </div>
  <div class="form-group">
    <%= f.submit class: 'btn btn-success' %>
  </div>
<% end %>

app/views/books/_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
      <tr>
        <td><%= link_to(book.user) do %>
          <%= image_tag book.user.get_profile_image(50, 50) %>
          <% end %>
        </td>
        <td>
          <%= link_to book_path(book.id) do %>
           <%= book.title %>
          <% end %>
        </td>
        <td><%= book.body %></td>
        <td class=<%= "favorite-" + book.id.to_s %>>
          <%= render "favorites/favorite", book: book %>
        </td>
        <td>
          <%= "コメント数:#{book.post_comments.count}" %>
        </td>
        <td><%= "閲覧数：#{book.view_counts.count}" %></td>
      </tr>
      <% end %>
  </tbody>
</table>

<div class="table_width">
  
  <%= form_with url: user_search_path(@user), method: :get, local:false do |f| %>
    <%= f.date_field :created_at %>
    <%= f.submit '検索', class: 'btn btn-primary'%>
  <% end %>
  
  <div id="search_result">
    <% if @search_book.present? %>
      <%= render 'users/search', search_book: @search_book %>
    <% end %>
  </div>
  
  <table class="table table-bordered">
    <h3>７日分の投稿数</h3>
    <thead>
      <tr>
        <th>６日前</th>
        <th>５日前</th>
        <th>４日前</th>
        <th>３日前</th>
        <th>２日前</th>
        <th>１日前</th>
        <th>今日</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= @books.created_6days.count %></td>
        <td><%= @books.created_5days.count %></td>
        <td><%= @books.created_4days.count %></td>
        <td><%= @books.created_3days.count %></td>
        <td><%= @books.created_2days.count %></td>
        <td><%= @yesterday_book.count %></td>
        <td><%= @today_book.count %></td>
      </tr>
    </tbody>
  </table>
  
 <canvas id="myLineChart"></canvas>
  <script>
    $(document).on('turbolinks:load', function() {
      var ctx = document.getElementById("myLineChart");
      var myLineChart = new Chart(ctx, {
        type: 'line',
        data: {
          labels: ['6日前', '5日前', '4日前', '3日前', '2日前', '1日前', '今日'],
          datasets: [
            {
              label: '投稿した本の数',
              data: [
                <%= @books.created_6days.count %>,
                <%= @books.created_5days.count %>, 
                <%= @books.created_4days.count %>, 
                <%= @books.created_3days.count %>, 
                <%= @books.created_2days.count %>, 
                <%= @yesterday_book.count %>, 
                <%= @today_book.count %>
              ],
              borderColor: "rgba(0,0,255,1)",
              backgroundColor: "rgba(0,0,0,0)",
              tension: 0.4
            }
          ],
        },
        options: {
          title: {
            display: true,
            text: "7日間の投稿数の比較"
          },
          responsive: true,
          scales: {
            y:{
              suggestedMin: 0,
              suggestedMax: 10
            },
            x:{
              stacked: true
            },
          },
        }
      });
    });
  </script>

</div>

app/views/books/edit.html.erb
<div class='container'>
  <% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this obj from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h1>Editing Book</h1>
  		<%= render 'form', book: @book %>
  		<%= link_to 'Show', @book %> |
  		<%= link_to 'Back', books_path, class: "back" %>
  </div>
</div>

app/views/books/index.html.erb
<div class="d-flex justify-content-center">
  <%= render 'searches/form' %>
</div>

<div class='container px-5 px-sm-0'>
   <% if @book_new.errors.any? %>
  <%= @book_new.errors.count %>件のエラーが発生しました
  <ul>
    <% @book_new.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @book_new %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'index', books: @books%>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="d-flex justify-content-center">
  <%= render 'searches/form' %>
</div>

<div class='container'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @books %>
    </div>
    <div class='col-md-8 offset-md-1'>
  		<h2>Book detail</h2>
  		<table class="table">
  		  <tr>
          <td><%= link_to(@book.user) do %>
            <%= image_tag @book.user.get_profile_image(100, 100) %><br>
            <%= @book.user.name %>
            <% end %>
          </td>
          <td><%= link_to @book.title, @book %></td>
          <td><%= @book.body %></td>
          <td class=<%= "favorite-" + @book.id.to_s %> >
            <%= render 'favorites/favorite', book: @book %>
          </td>
          <td class="count">
            <%= render 'post_comments/count', book: @book %>
          </td>
             <% if @user.id == current_user.id %>
            <td><%= link_to 'Edit', edit_book_path(@book), class: "btn btn-sm btn-success" %></td>
            <td><%= link_to 'Destroy', @book, method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger"%></td>
            <% else %>
            <td></td>
            <td></td>
            <% end %>
            <td><%= "閲覧数:#{@book.view_counts.count}" %></td>
          </tr>
      </table>
     
    <div class="comment">
      <%= render 'post_comments/post', book: @book %>
    </div>
    <!--コメント送信欄-->
    <div class="mt-2">
      <%= render "post_comments/comment", book: @book, post_comment: @post_comment %>
    </div>
    </div>
  </div>
</div>